<a href="https://colab.research.google.com/github/Mr-maike/Detection-alzheimers-disease/blob/main/alzheimer_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1) Configuração e Seleção de Imagens

1.1 Instalar as depedências em Python

In [ ]:
!pip install tensorflow opencv-python matplotlib

In [ ]:
!pip install --user nibabel

In [ ]:
import cv2
import imghdr
import nibabel as nib

In [ ]:
data_dir = 'data'
image_exts = ['nii']

In [ ]:
import tensorflow as tf
import os

gpus = tf.config.experimental.list_physical_devices('GPU')

for gpu in gpus:
  tf.config.experimental.set_memory_growth(gpu, True)

1.2 Selecionar as imagens errada

In [ ]:
#Acessar imagens do diretório
for image_class in os.listdir(data_dir):
  for image in os.listdir(os.path.join(data_dir, image_class)):
    print(image)

sub-001_T1w.nii


In [ ]:
img = nib.load('data/alzheimer/sub-001_T1w.nii')
print(img)

<class 'nibabel.nifti1.Nifti1Image'>
data shape (160, 192, 192)
affine: 
[[   1.19999695    0.            0.          -98.11138153]
 [   0.            1.25          0.          -89.59745789]
 [   0.            0.            1.25       -129.59745789]
 [   0.            0.            0.            1.        ]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 54
dim             : [  3 160 192 192   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.   1.2  1.25 1.25 3.   0.   0.   0.  ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset 

In [ ]:
for image_class in os.listdir(data_dir):
  for image in os.listdir(os.path.join(data_dir, image_class)):
    image_path = os.path.join(data_dir, image_class, image)
    try:
      img = cv2.imread(image_path)
      tip = imghdr.what(image_path)
      if tip not in image_exts:
        print('Imagem não está na lista de formatos {}'.format(image_path))
        os.remove(image.path)

    except Exception as e:
      print('Problema com o formato da imagem {}'.format(image_path))

Imagem não está na lista de formatos data/alzheimer/sub-001_T1w.nii
Problema com o formato da imagem data/alzheimer/sub-001_T1w.nii
